language: python
python: 
    - "3.8"

services:
    - docker

install: 
    - pip install -r requirements.txt

script: 
    - python -m pycodestyle DataBase.py
    - python test.py

deploy:
    provider: script
    script: bash deploy.sh
    on:
      branch: master