name: CI

on: push

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: bulv1ne/python-style-check@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: sudo -H pip install -r requirements.txt 
      - name: Run tests
        run: python3 tests.py
      - name: Login to docker.io
        run:  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t ${{ secrets.IMAGE }}:${GITHUB_REF:11} -f Dockerfile .
      - name: Push image to docker.io
        run: docker push ${{ secrets.IMAGE }}:${GITHUB_REF:11}